name: İhtiyaçlar
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
  - name: NodeJS
  uses: actions/setup-node@v4
  with:
  - name: Install Dependencies
  run: npm install @uppy/xhr-upload
